export const govStatus = {
  PROPOSAL_STATUS_VOTING_PERIOD: "PROPOSAL_STATUS_VOTING_PERIOD",
  PROPOSAL_STATUS_PASSED: "PROPOSAL_STATUS_PASSED",
  PROPOSAL_STATUS_REJECTED: "PROPOSAL_STATUS_REJECTED",
  PROPOSAL_STATUS_FAILED: "PROPOSAL_STATUS_FAILED",
};
