export { feature as botAdminFeature } from "./botAdmin.feature";
export { feature as startFeature } from "./start.feature";
export { feature as walletFeature } from "./wallet.feature";
export { feature as helpFeature } from "./help.feature";
export { feature as statisticFeature } from "./statistic.feature";
export { feature as proposalFeature } from "./proposal.feature";
export { feature as resourcesFeature } from "./resources.feature";
export { feature as notificationFeature } from "./notification.feature";
export { feature as assetsFeature } from "./assets.feature";
